### ISSUE TITLE
Move from framework to core

### ISSUE THREAD

**Issue by Anequit** [dk-raw/express-messenger#3]
By moving express messenger from .net framework to the latest .net core you can add the ability for users on mac or Linux to run it, but you also get a performance gain.

**Comment by Anequit** [comment]
I can move it to core if you give me the green light for it.

**Comment by Anequit** [comment]
Seems that there is no alternative for System.Windows.Forms for input in regards to the SendKeys method.

**Comment by dk-raw** [comment]
I could completely rewrite it and make it show up as human interface device with .net core but that will take way too much time than I am willing to spend on this project. Once again thanks for the recommendation.
